server:
  port: 8080

spring:
  datasource:
    ssm:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: rootroot
      url: jdbc:mysql://localhost:3306/sakila?serverTimezone=GMT%2B8
      username: root

logging:
  config: classpath:log4j2.xml

